name: Check-In

on:
  push:
    branches:
      - main

jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send check-in data
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"user": "${{ github.actor }}", "action": "check-in"}' \
        $WEBHOOK_URL
